-- 1. Creación de tablas, secuencias y restricciones. Incluye los DROP TABLE correspondientes al inicio para facilitar la re-ejecución.
CREATE TABLE AEROLINEAS (
    ID_AEROLINEA NUMBER(5) PRIMARY KEY,
    NOMBRE VARCHAR2(60) NOT NULL,
    PAIS VARCHAR2(50),
    CODIGO_IATA CHAR(2) UNIQUE
);

CREATE TABLE AVIONES (
    ID_AVION NUMBER(5) PRIMARY KEY,
    MATRICULA VARCHAR2(20) UNIQUE NOT NULL,
    MODELO VARCHAR2(60) NOT NULL,
    CAPACIDAD NUMBER(4) CHECK (CAPACIDAD > 0),
    ID_AEROLINEA NUMBER(5),
    FOREIGN KEY (ID_AEROLINEA) REFERENCES AEROLINEAS(ID_AEROLINEA)
);

CREATE TABLE TERMINALES (
    ID_TERMINAL NUMBER(5) PRIMARY KEY,
    NOMBRE VARCHAR2(40) NOT NULL,
    ZONA VARCHAR2(40)
);

CREATE TABLE PUERTAS_EMBARQUE (
    ID_PUERTA NUMBER(5) PRIMARY KEY,
    CODIGO_PUERTA VARCHAR2(10) UNIQUE NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'LIBRE'
        CHECK (ESTADO IN ('LIBRE', 'OCUPADA', 'MANTENIMIENTO')),
    ID_TERMINAL NUMBER(5),
    FOREIGN KEY (ID_TERMINAL) REFERENCES TERMINALES(ID_TERMINAL)
);

CREATE TABLE VUELOS (
    ID_VUELO NUMBER(5) PRIMARY KEY,
    CODIGO_VUELO VARCHAR2(10) UNIQUE NOT NULL,
    ORIGEN VARCHAR2(50) NOT NULL,
    DESTINO VARCHAR2(50) NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    ESTADO VARCHAR2(20) DEFAULT 'PROGRAMADO'
        CHECK (ESTADO IN ('PROGRAMADO', 'EMBARCANDO', 'RETRASADO', 'CANCELADO', 'FINALIZADO')),
    PRECIO NUMBER(8,2) CHECK (PRECIO >= 0),
    ID_AEROLINEA NUMBER(5),
    ID_AVION NUMBER(5),
    ID_PUERTA NUMBER(5),
    FOREIGN KEY (ID_AEROLINEA) REFERENCES AEROLINEAS(ID_AEROLINEA),
    FOREIGN KEY (ID_AVION) REFERENCES AVIONES(ID_AVION),
    FOREIGN KEY (ID_PUERTA) REFERENCES PUERTAS_EMBARQUE(ID_PUERTA),
    CHECK (ORIGEN <> DESTINO)
);

CREATE TABLE PASAJEROS (
    ID_PASAJERO NUMBER(5) PRIMARY KEY,
    DNI VARCHAR2(15) UNIQUE NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(80) NOT NULL,
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(80)
);

CREATE TABLE RESERVAS (
    ID_RESERVA NUMBER(5) PRIMARY KEY,
    ID_PASAJERO NUMBER(5),
    ID_VUELO NUMBER(5),
    FECHA_RESERVA DATE DEFAULT SYSDATE,
    ESTADO VARCHAR2(20) DEFAULT 'ACTIVA'
        CHECK (ESTADO IN ('ACTIVA', 'PAGADA', 'CANCELADA')),
    IMPORTE NUMBER(8,2) CHECK (IMPORTE >= 0),
    FOREIGN KEY (ID_PASAJERO) REFERENCES PASAJEROS(ID_PASAJERO),
    FOREIGN KEY (ID_VUELO) REFERENCES VUELOS(ID_VUELO),
    UNIQUE (ID_PASAJERO, ID_VUELO)
);

CREATE TABLE BILLETES (
    ID_BILLETE NUMBER(5) PRIMARY KEY,
    NUMERO_BILLETE VARCHAR2(20) UNIQUE NOT NULL,
    ASIENTO VARCHAR2(5),
    CLASE VARCHAR2(20)
        CHECK (CLASE IN ('TURISTA', 'BUSINESS')),
    ID_RESERVA NUMBER(5) UNIQUE,
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA)
);

CREATE TABLE EQUIPAJES (
    ID_EQUIPAJE NUMBER(5) PRIMARY KEY,
    ID_RESERVA NUMBER(5),
    PESO NUMBER(5,2) CHECK (PESO > 0),
    TIPO VARCHAR2(20)
        CHECK (TIPO IN ('MANO', 'FACTURADO')),
    ESTADO VARCHAR2(20) DEFAULT 'REGISTRADO'
        CHECK (ESTADO IN ('REGISTRADO', 'EMBARCADO', 'ENTREGADO', 'PERDIDO')),
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID_RESERVA)
);

CREATE TABLE EMPLEADOS (
    ID_EMPLEADO NUMBER(5) PRIMARY KEY,
    DNI VARCHAR2(15) UNIQUE NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(80) NOT NULL,
    PUESTO VARCHAR2(30)
        CHECK (PUESTO IN ('SEGURIDAD', 'FACTURACION', 'EMBARQUE', 'MANTENIMIENTO')),
    ID_TERMINAL NUMBER(5),
    FOREIGN KEY (ID_TERMINAL) REFERENCES TERMINALES(ID_TERMINAL)
);

CREATE TABLE TURNOS_EMPLEADOS (
    ID_TURNO NUMBER(5) PRIMARY KEY,
    ID_EMPLEADO NUMBER(5),
    FECHA_TURNO DATE NOT NULL,
    TURNO VARCHAR2(20)
        CHECK (TURNO IN ('MANANA', 'TARDE', 'NOCHE')),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE LOG_VUELOS (
    ID_LOG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_VUELO NUMBER(5),
    ESTADO_ANTES VARCHAR2(20),
    ESTADO_DESPUES VARCHAR2(20),
    FECHA_CAMBIO DATE DEFAULT SYSDATE,
    USUARIO_BD VARCHAR2(50) DEFAULT USER
);